server:
  port: 8081

spring:
  application:
    name: Microservice Fornecedor
  datasource:
    url: jdbc:mysql://localhost:3306/fornecedor?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

